.TH MINDUSTRY 6 "" "mindustry" "Games"
.SH NAME
mindustry \- hybrid tower-defense sandbox factory game
.SH SYNOPSIS
.B mindustry
.SH DESCRIPTION
Mindustry is a hybrid tower-defense sandbox factory game. Players
defend outposts by mining resources, building automated supply
chains, and constructing defensive structures, while also being
able to fight against other players in multiplayer PvP mode.
.PP
Running
.B mindustry
launches the graphical desktop client.
.SH SEE ALSO
.BR mindustry-server (6)
.SH AUTHOR
Anuken and contributors <https://github.com/Anuken/Mindustry>
