.TH MINDUSTRY-SERVER 6 "" "mindustry-server" "Games"
.SH NAME
mindustry-server \- headless dedicated server for Mindustry
.SH SYNOPSIS
.B mindustry-server
.SH DESCRIPTION
Runs a headless dedicated server for Mindustry, a hybrid
tower-defense sandbox factory game. Players connecting to the
server can cooperate to build shared factories or fight against
each other in PvP combat.
.PP
The server reads commands interactively from standard input;
type
.B help
at the prompt for a list of available console commands.
.SH SEE ALSO
.BR mindustry (6)
.SH AUTHOR
Anuken and contributors <https://github.com/Anuken/Mindustry>
